package com.example.getoutthere.utils;

// The following code used information from https://developer.android.com/training/app-links/create-deeplinks#java and https://www.geeksforgeeks.org/android/deep-linking-in-android-with-example/, 2026-03-12

import android.content.Intent;
import android.net.Uri;
import android.os.Bundle;

import androidx.appcompat.app.AppCompatActivity;

import com.example.getoutthere.event.EventDetailsActivity;

/**
 * Acts as a router and dispatcher for Android Deep Links.
 * <p>
 * This Activity intercepts incoming deep link URLs, extracts the necessary
 * payload (such as an event ID), and seamlessly redirects the user to the
 * appropriate screen (EventDetailsActivity). It utilizes a Dispatcher pattern
 * to handle routing without maintaining its own UI.
 * <p>
 * Outstanding Issues:
 * - Currently lacks a fallback mechanism or error screen if the deep link is
 * malformed or the parsed event ID does not exist in the database.
 * <p>
 * Note: Initial Javadoc and introductory comments generated by Gemini.
 */
public class DeepLinkRouterActivity extends AppCompatActivity {

    /**
     * Initializes the Activity, parses the incoming Intent data for a deep link URI,
     * and routes the user to the EventDetailsActivity if a valid ID is found.
     *
     * @param savedInstanceState If the activity is being re-initialized after previously being
     * shut down then this Bundle contains the data it most recently
     * supplied. Otherwise it is null.
     */
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        Uri data = getIntent().getData();

        if (data != null) {
            String eventId = data.getLastPathSegment();

            if (eventId != null && !eventId.isEmpty()) {
                Intent intent = new Intent(this, EventDetailsActivity.class);
                intent.putExtra("eventId", eventId);
                startActivity(intent);
            }
        }

        finish();
    }
}