package com.example.getoutthere.utils;

import android.graphics.Bitmap;

import com.google.zxing.BarcodeFormat;
import com.google.zxing.WriterException;
import com.journeyapps.barcodescanner.BarcodeEncoder;

// The following code used information from https://www.geeksforgeeks.org/android/how-to-generate-qr-code-in-android/, 2026-03-12

/**
 * Utility class for generating QR codes.
 * <p>
 * This class serves as a utility pattern that abstracts the implementation details
 * of the ZXing BarcodeEncoder library. It accepts a raw string (like an event hash
 * or ID) and encodes it into a visual Bitmap QR code that can be displayed in an ImageView.
 * <p>
 * Outstanding Issues:
 * - The dimensions (400x400) are hardcoded, limiting flexibility if a larger or
 * smaller Bitmap is needed for different UI layouts.
 * <p>
 * Note: Initial Javadoc and introductory comments generated by Gemini.
 */
public class QRCodeGenerator {

    /**
     * Encodes a given text string into a 400x400 Bitmap QR Code.
     *
     * @param text The string content to be encoded into the QR code.
     * @return A Bitmap image containing the generated QR code.
     * @throws WriterException If the encoding process fails.
     */
    public Bitmap generateQRCode(String text) throws WriterException {
        BarcodeEncoder barcodeEncoder = new BarcodeEncoder();
        return barcodeEncoder.encodeBitmap(text, BarcodeFormat.QR_CODE, 400, 400);
    }
}