package com.example.getoutthere.event;

import android.content.Intent;
import android.os.Bundle;
import android.widget.ArrayAdapter;
import android.widget.ListView;

import androidx.activity.EdgeToEdge;
import androidx.appcompat.app.AppCompatActivity;
import androidx.core.graphics.Insets;
import androidx.core.view.ViewCompat;
import androidx.core.view.WindowInsetsCompat;

import com.example.getoutthere.R;
import com.example.getoutthere.navigation.NavBottomHelper;
import com.google.android.material.bottomnavigation.BottomNavigationView;
import com.google.firebase.firestore.FirebaseFirestore;
import com.google.firebase.firestore.QueryDocumentSnapshot;

import java.util.ArrayList;
import java.util.List;

/**
 * Displays a list of all currently available events the user can enroll in.
 * <p>
 * This Activity acts as a Control layer mapping data to a ListView. It queries
 * the Firestore database for all events, populates a custom ArrayAdapter, and
 * handles click events to route the user to the EventDetailsActivity for the
 * selected event.
 * <p>
 * Outstanding Issues:
 * - Currently fetches all events in a single query. If the database scales up,
 * this will need to implement pagination to prevent performance degradation.
 * - Direct database access in the Activity bypasses standard Repository patterns.
 * <p>
 * Note: Initial Javadoc and introductory comments generated by Gemini.
 */
public class EventListActivity extends AppCompatActivity {

    private ListView listView;
    private List<Event> events = new ArrayList<>();
    private List<String> eventNames = new ArrayList<>();
    private FirebaseFirestore db = FirebaseFirestore.getInstance();

    /**
     * Initializes the Activity, fetches the collection of events from Firestore,
     * maps them to the local lists, and binds the data to the ListView via an ArrayAdapter.
     *
     * @param savedInstanceState If the activity is being re-initialized after previously being
     * shut down then this Bundle contains the data it most recently
     * supplied. Otherwise it is null.
     */
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        EdgeToEdge.enable(this);
        setContentView(R.layout.activity_event_list);
        ViewCompat.setOnApplyWindowInsetsListener(findViewById(R.id.main), (v, insets) -> {
            Insets systemBars = insets.getInsets(WindowInsetsCompat.Type.systemBars());
            v.setPadding(systemBars.left, systemBars.top, systemBars.right, systemBars.bottom);
            return insets;



        });

        listView = findViewById(R.id.listOfEvents);

        // Fetch events from Firestore
        db.collection("events").get().addOnSuccessListener(queryDocumentSnapshots -> {
            events.clear();
            eventNames.clear();
            for (QueryDocumentSnapshot doc : queryDocumentSnapshots) {
                Event event = doc.toObject(Event.class);
                event.setId(doc.getId());
                events.add(event);
                eventNames.add(event.getName());
            }

            ArrayAdapter<String> adapter = new ArrayAdapter<>(this, R.layout.item_history_row, eventNames);
            listView.setAdapter(adapter);
        });

        // On click, go to EventDetailsActivity
        listView.setOnItemClickListener((parent, view, position, id) -> {
            Event event = events.get(position);
            Intent intent = new Intent(EventListActivity.this, EventDetailsActivity.class);
            intent.putExtra("eventId", event.getId());
            startActivity(intent);
        });

        BottomNavigationView bottomNav = findViewById(R.id.bottomNavigation);
        NavBottomHelper.setupBottomNav(this, bottomNav, R.id.nav_home);

    }
}