package com.example.getoutthere.event;

import android.content.Intent;
import android.os.Bundle;
import android.text.Editable;
import android.text.TextUtils;
import android.text.TextWatcher;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageButton;
import android.widget.ListView;
import android.widget.Toast;

import androidx.activity.EdgeToEdge;
import androidx.appcompat.app.AppCompatActivity;
import androidx.core.graphics.Insets;
import androidx.core.view.ViewCompat;
import androidx.core.view.WindowInsetsCompat;

import com.example.getoutthere.R;
import com.example.getoutthere.navigation.NavBottomHelper;
import com.google.android.material.bottomnavigation.BottomNavigationView;
import com.google.firebase.firestore.FirebaseFirestore;
import com.google.firebase.firestore.QueryDocumentSnapshot;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

/**
 * Displays a list of all currently available events the user can enroll in.
 * <p>
 * This Activity acts as a Control layer mapping data to a ListView. It queries
 * the Firestore database for all events, populates a custom ArrayAdapter, and
 * handles click events to route the user to the EventDetailsActivity for the
 * selected event.
 * <p>
 * Outstanding Issues:
 * - Currently fetches all events in a single query. If the database scales up,
 * this will need to implement pagination to prevent performance degradation.
 * - Direct database access in the Activity bypasses standard Repository patterns.
 * <p>
 * Note: Initial Javadoc and introductory comments generated by Gemini.
 */
public class EventListActivity extends AppCompatActivity {

    private ListView listView;
    private final List<Event> allEvents = new ArrayList<>();
    private final List<Event> filteredEvents = new ArrayList<>();

    private FirebaseFirestore db = FirebaseFirestore.getInstance();

    private EventDiscoverAdapter adapter;


    private EditText searchInput;
    private Button filterButton;

    /**
     * Initializes the Activity, fetches the collection of events from Firestore,
     * maps them to the local lists, and binds the data to the ListView via a custom EventDiscoverAdapter.
     *
     * @param savedInstanceState If the activity is being re-initialized after previously being
     * shut down then this Bundle contains the data it most recently
     * supplied. Otherwise it is null.
     */
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        EdgeToEdge.enable(this);
        setContentView(R.layout.activity_event_list);
        ViewCompat.setOnApplyWindowInsetsListener(findViewById(R.id.main), (v, insets) -> {
            Insets systemBars = insets.getInsets(WindowInsetsCompat.Type.systemBars());
            v.setPadding(systemBars.left, systemBars.top, systemBars.right, systemBars.bottom);
            return insets;



        });

        listView = findViewById(R.id.listOfEvents);
        searchInput = findViewById(R.id.searchInput);
        filterButton = findViewById(R.id.filterButton);
        adapter = new EventDiscoverAdapter(this, filteredEvents);
        listView.setAdapter(adapter);

        // fetch event from db
        db.collection("events").get().addOnSuccessListener(queryDocumentSnapshots -> {
            allEvents.clear();

            for (QueryDocumentSnapshot doc : queryDocumentSnapshots) {
                Event event = doc.toObject(Event.class);
                event.setId(doc.getId());
                allEvents.add(event);
            }

            filteredEvents.clear();
            filteredEvents.addAll(allEvents);
            adapter.notifyDataSetChanged();
        });


        // Original search/filter logic generated with AI.
        // Refactored to align with the current project structure and UI redesign. Yousaf - April 4 2026
        searchInput.addTextChangedListener(new TextWatcher() {
            @Override
            public void beforeTextChanged(CharSequence s, int start, int count, int after) {
            }

            @Override
            public void onTextChanged(CharSequence s, int start, int before, int count) {
                applySearch();
            }

            @Override
            public void afterTextChanged(Editable s) {
            }
        });

        filterButton.setOnClickListener(v -> {
            Toast.makeText(this, "Filter options coming soon", Toast.LENGTH_SHORT).show();
        });

        // click on event to open event details
        listView.setOnItemClickListener((parent, view, position, id) -> {
            Event event = filteredEvents.get(position);
            Intent intent = new Intent(EventListActivity.this, EventDetailsActivity.class);
            intent.putExtra("eventId", event.getId());
            startActivity(intent);
        });

        BottomNavigationView bottomNav = findViewById(R.id.bottomNavigation);
        NavBottomHelper.setupBottomNav(this, bottomNav, R.id.nav_home);

    }

    /**
     * Applies all active filters and the current search query together against
     * the full events list, then updates the ListView adapter with the results.
     *
     * @param query the current search string entered by the user
     */
    // The following code is from Anthropic, Claude, "Add filter fragment with eventType, minCapacity, and date range to EventListActivity", 2026-04-02
    // Refactored to align with the current project structure and UI redesign. Yousaf - April 4 2026
    private void applySearch() {
        String query = searchInput.getText().toString().trim().toLowerCase(Locale.getDefault());

        filteredEvents.clear();

        if (TextUtils.isEmpty(query)) {
            filteredEvents.addAll(allEvents);
        } else {
            for (Event event : allEvents) {
                String name = event.getName() != null
                        ? event.getName().toLowerCase(Locale.getDefault())
                        : "";

                String address = event.getAddress() != null
                        ? event.getAddress().toLowerCase(Locale.getDefault())
                        : "";

                if (name.contains(query) || address.contains(query)) {
                    filteredEvents.add(event);
                }
            }
        }

        adapter.notifyDataSetChanged();
    }

    /**
     * Applies all active filters and the current search query together against
     * the full events list, then updates the ListView adapter with the results.
     *
     * @param query the current search string entered by the user
     */
    // The following code is from Anthropic, Claude, "Add filter fragment with eventType, minCapacity, and date range to EventListActivity", 2026-04-02
    private void applyFiltersAndSearch(String query) {
        List<Event> result = new ArrayList<>();

        for (Event e : events) {
            // Search filter
            if (!query.isEmpty()) {
                if (!e.getName().toLowerCase().contains(query) &&
                        !e.getDescription().toLowerCase().contains(query)) {
                    continue;
                }
            }

            // Event type filter
            if (activeEventType != null && !activeEventType.equals("All")) {
                if (e.getEventType() == null || !e.getEventType().equalsIgnoreCase(activeEventType)) {
                    continue;
                }
            }

            // Minimum capacity filter
            if (e.getCapacity() < activeMinCapacity) {
                continue;
            }

            // Start date range filter
            if (e.getStartDate() != null) {
                long startMillis = e.getStartDate().toDate().getTime();
                if (startMillis < activeMinStartDate || startMillis > activeMaxStartDate) {
                    continue;
                }
            }

            result.add(e);
        }

        displayedEvents[0] = result;
        EventAdapter adapter = new EventAdapter(this, result);
        listView.setAdapter(adapter);
    }
}