package com.example.getoutthere.event;

import android.os.Bundle;
import android.provider.Settings;
import android.widget.Button;
import android.widget.TextView;
import android.widget.Toast;
import android.widget.ImageView;
import com.bumptech.glide.Glide;

import androidx.activity.EdgeToEdge;
import androidx.appcompat.app.AppCompatActivity;
import androidx.core.graphics.Insets;
import androidx.core.view.ViewCompat;
import androidx.core.view.WindowInsetsCompat;

import com.example.getoutthere.R;
import com.example.getoutthere.models.EntrantProfile;
import com.google.firebase.Timestamp;
import com.google.firebase.firestore.FieldValue;
import com.google.firebase.firestore.FirebaseFirestore;

import java.text.SimpleDateFormat;
import java.util.HashMap;

/**
 * Displays detailed information about a specific event.
 * <p>
 * This Activity serves as a Control and View class that pulls specific event data
 * from Firestore and populates the UI. It handles the core logic for allowing
 * users to join or leave the event's waiting list, updating both the local UI state
 * and the remote Firestore database atomically.
 * <p>
 * Outstanding Issues:
 * - Direct database access is performed within the UI layer, which loosely violates
 * MVC/MVVM separation of concerns. This could be refactored into a Repository.
 * - The logic allows joining a waitlist but does not yet implement the final lottery selection.
 * <p>
 * Note: Initial Javadoc and introductory comments generated by Gemini.
 */
public class EventDetailsActivity extends AppCompatActivity {
    private TextView eventName, eventAddress, eventDateRange, eventCapacity, eventFee, eventDrawDate;
    private Button btnToggleWaitingList, btnBack;

    private String eventId;
    Event event;
    private EntrantProfile entrant;

    boolean isOnWaitingList = false;

    private FirebaseFirestore db = FirebaseFirestore.getInstance();

    /**
     * Initializes the Activity, fetches the Entrant's device ID, parses the event ID
     * passed via Intent, and queries Firestore to populate the UI. Sets up listeners
     * for joining/leaving the waitlist.
     *
     * @param savedInstanceState If the activity is being re-initialized after previously being
     * shut down then this Bundle contains the data it most recently
     * supplied. Otherwise it is null.
     */
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        EdgeToEdge.enable(this);
        setContentView(R.layout.activity_event_details);

        // Handle window insets
        ViewCompat.setOnApplyWindowInsetsListener(findViewById(R.id.main), (v, insets) -> {
            Insets systemBars = insets.getInsets(WindowInsetsCompat.Type.systemBars());
            v.setPadding(systemBars.left, systemBars.top, systemBars.right, systemBars.bottom);
            return insets;
        });

        // UI elements
        eventName = findViewById(R.id.EventName);
        eventAddress = findViewById(R.id.EventAddress);
        eventDateRange = findViewById(R.id.EventDateRange);
        eventCapacity = findViewById(R.id.EventCapacity);
        eventFee = findViewById(R.id.EventSignupFee);
        eventDrawDate = findViewById(R.id.EventDrawDate);
        btnToggleWaitingList = findViewById(R.id.btnToggleWaitingList);
        btnBack = findViewById(R.id.EventDetailsBackButton);

        // Entrant info
        String deviceId = Settings.Secure.getString(getContentResolver(), Settings.Secure.ANDROID_ID);
        entrant = new EntrantProfile();
        entrant.setDeviceId(deviceId);

        // Event ID from intent
        eventId = getIntent().getStringExtra("eventId");

        // Back button
        btnBack.setOnClickListener(v -> finish());

        //  Lottery Info link
        TextView btnLotteryInfo = findViewById(R.id.btnLotteryInfo);
        btnLotteryInfo.setOnClickListener(v -> showLotteryCriteriaDialog());

        // Fetch event from Firestore
        db.collection("events").document(eventId).get().addOnSuccessListener(documentSnapshot -> {
            if (documentSnapshot.exists()) {
                event = documentSnapshot.toObject(Event.class);
                event.setId(documentSnapshot.getId());

                // Set UI
                eventName.setText(event.getName());
                eventAddress.setText(event.getAddress());
                eventFee.setText("Signup fee: $" + event.getSignupFee());

                // Check if the event has a poster
                ImageView eventPoster = findViewById(R.id.EventPoster);
                if (event.getPosterUrl() != null && !event.getPosterUrl().isEmpty()) {
                    Glide.with(EventDetailsActivity.this)
                            .load(event.getPosterUrl())
                            .into(eventPoster);
                }

                // Date & time range
                if (event.getStartDate() != null && event.getEndDate() != null) {
                    SimpleDateFormat timeFmt = new SimpleDateFormat("hh:mm a");
                    SimpleDateFormat dateFmt = new SimpleDateFormat("MM/dd");
                    String dateRange = timeFmt.format(event.getStartDate().toDate())
                            + "-" + timeFmt.format(event.getEndDate().toDate())
                            + " from " + dateFmt.format(event.getStartDate().toDate())
                            + "-" + dateFmt.format(event.getEndDate().toDate());
                    eventDateRange.setText(dateRange);
                }

                // Draw date
                if (event.getDrawDate() != null) {
                    String drawStr = new SimpleDateFormat("MM/dd/yyyy").format(event.getDrawDate().toDate());
                    eventDrawDate.setText("Draws on " + drawStr);
                }

                // Spots available
                updateSpotsUI();

                // Check if user is already on waiting list
                db.collection("events")
                        .document(eventId)
                        .collection("waitingList")
                        .document(entrant.getDeviceId())
                        .get()
                        .addOnSuccessListener(doc -> {
                            isOnWaitingList = doc.exists();
                            updateToggleButton();
                        });
            }
        });

        // Toggle waiting list button
        btnToggleWaitingList.setOnClickListener(v -> {
            if (event == null) return;

            if (!isOnWaitingList) {

                // Check registration period before allowing join
                if (!isRegistrationOpen()) {
                    return;
                }

                // If event is full, user cannot join
                if (event.getCurrentWaitlistCount() >= event.getCapacity()) {
                    Toast.makeText(EventDetailsActivity.this, "Event is full! Cannot join waiting list.", Toast.LENGTH_SHORT).show();
                    return;
                }

                // Join waiting list
                db.collection("events")
                        .document(event.getId())
                        .collection("waitingList")
                        .document(entrant.getDeviceId())
                        .set(new HashMap<String, Object>() {{
                            put("name", entrant.getName());
                            put("email", entrant.getEmail());
                            put("phone", entrant.getPhoneNumber());
                        }})
                        .addOnSuccessListener(aVoid -> {
                            isOnWaitingList = true;

                            db.collection("events")
                                    .document(event.getId())
                                    .update("currentWaitlistCount", FieldValue.increment(1));

                            event.setCurrentWaitlistCount(event.getCurrentWaitlistCount() + 1);
                            updateSpotsUI();
                            updateToggleButton();
                            Toast.makeText(EventDetailsActivity.this, "Joined waiting list!", Toast.LENGTH_SHORT).show();
                        })
                        .addOnFailureListener(e -> Toast.makeText(EventDetailsActivity.this, "Failed to join waiting list", Toast.LENGTH_SHORT).show());
            } else {
                // Leave waiting list
                db.collection("events")
                        .document(event.getId())
                        .collection("waitingList")
                        .document(entrant.getDeviceId())
                        .delete()
                        .addOnSuccessListener(aVoid -> {
                            isOnWaitingList = false;

                            db.collection("events")
                                    .document(event.getId())
                                    .update("currentWaitlistCount", FieldValue.increment(-1));

                            event.setCurrentWaitlistCount(event.getCurrentWaitlistCount() - 1);
                            updateSpotsUI();
                            updateToggleButton();
                            Toast.makeText(EventDetailsActivity.this, "Left waiting list!", Toast.LENGTH_SHORT).show();
                        })
                        .addOnFailureListener(e -> Toast.makeText(EventDetailsActivity.this, "Failed to leave waiting list", Toast.LENGTH_SHORT).show());
            }
        });


    }

    /**
     * Calculates the remaining spots available by subtracting the current waitlist
     * count from the total capacity, and updates the UI TextView accordingly.
     */
    void updateSpotsUI() {
        int spotsAvailable = event.getCapacity() - event.getCurrentWaitlistCount();
        eventCapacity.setText(spotsAvailable + "/" + event.getCapacity() + " spots available");
    }

    /**
     * Checks whether the current time falls within the event's registration period.
     *
     * @return true if registration is currently open, false otherwise
     */
    private boolean isRegistrationOpen() {
        Timestamp now = Timestamp.now();

        if (event.getRegistrationStart() != null &&
                now.compareTo(event.getRegistrationStart()) < 0) {
            Toast.makeText(this, "Registration has not opened yet.", Toast.LENGTH_SHORT).show();
            return false;
        }

        if (event.getRegistrationEnd() != null &&
                now.compareTo(event.getRegistrationEnd()) > 0) {
            Toast.makeText(this, "Registration period has ended.", Toast.LENGTH_SHORT).show();
            return false;
        }

        return true;
    }

    /**
     * Displays an info about the lottery selection criteria
     */
    private void showLotteryCriteriaDialog() {
        new androidx.appcompat.app.AlertDialog.Builder(this)
                .setTitle("Lottery Guidelines") // Set title
                .setMessage("Selection for this event is processed via a randomized lottery system.\n\n" + //message
                        "• Joining the waitlist does not guarantee entry.\n" +
                        "• When the draw date occurs, entrants are selected entirely at random up to the event's capacity limit.\n" +
                        "• If selected, you will receive a notification to finalize your enrollment.")
                .setPositiveButton("Understood", null) // dismiss message
                .show();
    }

    /**
     * Toggles the UI state of the waitlist button, changing its text and color
     * depending on whether the current user is already on the waiting list.
     */
    private void updateToggleButton() {
        if (isOnWaitingList) {
            btnToggleWaitingList.setText("Leave Waiting List");
            btnToggleWaitingList.setBackgroundTintList(getResources().getColorStateList(R.color.red, null));
        } else {
            btnToggleWaitingList.setText("Join Waiting List");
            btnToggleWaitingList.setBackgroundTintList(getResources().getColorStateList(R.color.lightGreen, null));
        }
    }
}