package com.example.getoutthere.event;

import com.google.firebase.Timestamp;

/**
 * Represents an Event entity within the application.
 * <p>
 * This class acts as a Model and Data Transfer Object (DTO) containing all the
 * specifics of an event (name, capacity, dates, waitlist limits). It is designed
 * to be easily serialized and deserialized by Firebase Firestore.
 * <p>
 * Outstanding Issues:
 * - Currently operates as a pure data container and lacks internal data validation
 * (e.g., ensuring capacity > 0 or that endDate is strictly after startDate) within the setters.
 * <p>
 * Note: Initial Javadoc and introductory comments generated by Gemini.
 */
public class Event {
    private String id;
    private String organizerId;
    private String name;
    private String description;
    private String address;

    private Timestamp startDate;
    private Timestamp endDate;
    private Timestamp drawDate;

    private Timestamp registrationStart;
    private Timestamp registrationEnd;

    private int currentWaitlistCount;
    private int capacity;
    private Integer waitlistLimit;

    private double signupFee;

    private String posterUrl;
    private String qrCodeContent;
    private String status;

    /**
     * Default constructor required for Firebase Firestore serialization.
     */
    public Event() {}

    /**
     * Gets the unique identifier for the event.
     * @return A string representing the event ID.
     */
    public String getId() { return id; }

    /**
     * Sets the unique identifier for the event.
     * @param id The string ID to assign to this event.
     */
    public void setId(String id) { this.id = id; }

    /**
     * Gets the ID of the organizer who created the event.
     * @return A string representing the organizer's device ID.
     */
    public String getOrganizerId() { return organizerId; }

    /**
     * Sets the ID of the organizer creating the event.
     * @param organizerId The string representing the organizer's device ID.
     */
    public void setOrganizerId(String organizerId) { this.organizerId = organizerId; }

    /**
     * Gets the name of the event.
     * @return The event name.
     */
    public String getName() { return name; }

    /**
     * Sets the name of the event.
     * @param name The new name for the event.
     */
    public void setName(String name) { this.name = name; }

    /**
     * Gets the description of the event.
     * @return The event description.
     */
    public String getDescription() { return description; }

    /**
     * Sets the description of the event.
     * @param description The new description.
     */
    public void setDescription(String description) { this.description = description; }

    /**
     * Gets the physical address or location of the event.
     * @return The event address.
     */
    public String getAddress() { return address; }

    /**
     * Sets the physical address or location of the event.
     * @param address The new address.
     */
    public void setAddress(String address) { this.address = address; }

    /**
     * Gets the start date and time of the event.
     * @return A Firebase Timestamp representing the start date.
     */
    public Timestamp getStartDate() { return startDate; }

    /**
     * Sets the start date and time of the event.
     * @param startDate The Firebase Timestamp for the start date.
     */
    public void setStartDate(Timestamp startDate) { this.startDate = startDate; }

    /**
     * Gets the end date and time of the event.
     * @return A Firebase Timestamp representing the end date.
     */
    public Timestamp getEndDate() { return endDate; }

    /**
     * Sets the end date and time of the event.
     * @param endDate The Firebase Timestamp for the end date.
     */
    public void setEndDate(Timestamp endDate) { this.endDate = endDate; }

    /**
     * Gets the date the lottery draw occurs.
     * @return A Firebase Timestamp representing the draw date.
     */
    public Timestamp getDrawDate() { return drawDate; }

    /**
     * Sets the date the lottery draw occurs.
     * @param drawDate The Firebase Timestamp for the draw date.
     */
    public void setDrawDate(Timestamp drawDate) { this.drawDate = drawDate; }

    /**
     * Gets the date when registration opens.
     * @return A Firebase Timestamp representing the registration start.
     */
    public Timestamp getRegistrationStart() { return registrationStart; }

    /**
     * Sets the date when registration opens.
     * @param registrationStart The Firebase Timestamp for the registration start.
     */
    public void setRegistrationStart(Timestamp registrationStart) { this.registrationStart = registrationStart; }

    /**
     * Gets the date when registration closes.
     * @return A Firebase Timestamp representing the registration end.
     */
    public Timestamp getRegistrationEnd() { return registrationEnd; }

    /**
     * Sets the date when registration closes.
     * @param registrationEnd The Firebase Timestamp for the registration end.
     */
    public void setRegistrationEnd(Timestamp registrationEnd) { this.registrationEnd = registrationEnd; }

    /**
     * Gets the maximum number of attendees allowed for the event.
     * @return The event capacity.
     */
    public int getCapacity() { return capacity; }

    /**
     * Sets the maximum number of attendees allowed for the event.
     * @param capacity The integer capacity.
     */
    public void setCapacity(int capacity) { this.capacity = capacity; }

    /**
     * Gets the current number of users on the waiting list.
     * @return The current waitlist count.
     */
    public int getCurrentWaitlistCount() { return currentWaitlistCount; }

    /**
     * Sets the current number of users on the waiting list.
     * @param currentWaitlistCount The integer waitlist count.
     */
    public void setCurrentWaitlistCount(int currentWaitlistCount) { this.currentWaitlistCount = currentWaitlistCount; }

    /**
     * Gets the maximum limit for the waiting list, if one exists.
     * @return The waitlist limit, or null if uncapped.
     */
    public Integer getWaitlistLimit() { return waitlistLimit; }

    /**
     * Sets the maximum limit for the waiting list.
     * @param waitlistLimit The integer limit, or null for uncapped.
     */
    public void setWaitlistLimit(Integer waitlistLimit) { this.waitlistLimit = waitlistLimit; }

    /**
     * Gets the monetary fee required to sign up for the event.
     * @return The signup fee as a double.
     */
    public double getSignupFee() { return signupFee; }

    /**
     * Sets the monetary fee required to sign up for the event.
     * @param signupFee The double representing the fee.
     */
    public void setSignupFee(double signupFee) { this.signupFee = signupFee; }

    /**
     * Gets the URL of the event's promotional poster image.
     * @return A string URL linking to the poster image.
     */
    public String getPosterUrl() { return posterUrl; }

    /**
     * Sets the URL of the event's promotional poster image.
     * @param posterUrl The string URL for the image.
     */
    public void setPosterUrl(String posterUrl) { this.posterUrl = posterUrl; }

    /**
     * Gets the hashed content string used for generating the event's QR code.
     * @return The QR code content string.
     */
    public String getQrCodeContent() { return qrCodeContent; }

    /**
     * Sets the hashed content string used for generating the event's QR code.
     * @param qrCodeContent The string content to encode.
     */
    public void setQrCodeContent(String qrCodeContent) { this.qrCodeContent = qrCodeContent; }

    /**
     * Gets the current status of the event (e.g., open, closed, drawn).
     * @return The status string.
     */
    public String getStatus() { return status; }

    /**
     * Sets the current status of the event.
     * @param status The status string.
     */
    public void setStatus(String status) { this.status = status; }
}