package com.example.getoutthere.event;

import android.os.Bundle;
import android.provider.Settings;
import android.view.View;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.TextView;
import android.widget.Toast;
import android.widget.ImageView;
import com.bumptech.glide.Glide;
import android.widget.FrameLayout;

import androidx.activity.EdgeToEdge;
import androidx.appcompat.app.AppCompatActivity;
import androidx.core.graphics.Insets;
import androidx.core.view.ViewCompat;
import androidx.core.view.WindowInsetsCompat;

import com.example.getoutthere.R;
import com.example.getoutthere.models.EntrantProfile;
import com.google.firebase.Timestamp;
import com.google.firebase.firestore.DocumentSnapshot;
import com.google.firebase.firestore.FieldValue;
import com.google.firebase.firestore.FirebaseFirestore;

import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Objects;

/**
 * Displays detailed information about a specific event.
 * <p>
 * This Activity serves as a Control and View class that pulls specific event data
 * from Firestore and populates the UI. It handles the core logic for allowing
 * users to join or leave the event's waiting list, updating both the local UI state
 * and the remote Firestore database atomically.
 * <p>
 * Outstanding Issues:
 * - Direct database access is performed within the UI layer, which loosely violates
 * MVC/MVVM separation of concerns. This could be refactored into a Repository.
 * - The logic allows joining a waitlist but does not yet implement the final lottery selection.
 * <p>
 * Note: Initial Javadoc and introductory comments generated by Gemini.
 */
public class EventDetailsActivity extends AppCompatActivity {
    private TextView eventName, eventAddress, eventDateRange, eventCapacity, eventFee, eventDrawDate, eventDescription, eventType;
    private Button btnToggleWaitingList, btnViewComments;

    private FrameLayout backButton;

    private String eventId;
    Event event;
    private EntrantProfile entrant;

    boolean isOnWaitingList = false;
    boolean isAOrganizer = false;

    private FirebaseFirestore db = FirebaseFirestore.getInstance();

    /**
     * Initializes the Activity, fetches the Entrant's device ID, parses the event ID
     * passed via Intent, and queries Firestore to populate the UI. Sets up listeners
     * for joining/leaving the waitlist.
     *
     * @param savedInstanceState If the activity is being re-initialized after previously being
     * shut down then this Bundle contains the data it most recently
     * supplied. Otherwise it is null.
     */
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        EdgeToEdge.enable(this);
        setContentView(R.layout.activity_event_details);

        // Handle window insets
        ViewCompat.setOnApplyWindowInsetsListener(findViewById(R.id.main), (v, insets) -> {
            Insets systemBars = insets.getInsets(WindowInsetsCompat.Type.systemBars());
            v.setPadding(systemBars.left, systemBars.top, systemBars.right, systemBars.bottom);
            return insets;
        });

        // UI elements
        eventName = findViewById(R.id.EventName);
        eventAddress = findViewById(R.id.EventAddress);
        eventDateRange = findViewById(R.id.EventDateRange);
        eventCapacity = findViewById(R.id.EventCapacity);
        eventFee = findViewById(R.id.EventSignupFee);
        eventDrawDate = findViewById(R.id.EventDrawDate);
        eventDescription = findViewById(R.id.EventDescription);
        eventType = findViewById(R.id.EventType);
        btnToggleWaitingList = findViewById(R.id.btnToggleWaitingList);

        // Entrant info
        String deviceId = Settings.Secure.getString(getContentResolver(), Settings.Secure.ANDROID_ID);
        entrant = new EntrantProfile();
        entrant.setDeviceId(deviceId);

        // Event ID from intent
        eventId = getIntent().getStringExtra("eventId");

        backButton = findViewById(R.id.backButton);
        backButton.setOnClickListener(v -> finish());

        //  Lottery Info link
        Button btnLotteryInfo = findViewById(R.id.btnLotteryInfo);
        btnLotteryInfo.setOnClickListener(v -> showLotteryCriteriaDialog());

        // Fetch event from Firestore
        db.collection("events").document(eventId).get().addOnSuccessListener(documentSnapshot -> {
            if (documentSnapshot.exists()) {
                event = documentSnapshot.toObject(Event.class);
                event.setId(documentSnapshot.getId());

                // Set UI
                eventName.setText(event.getName());
                eventDescription.setText(event.getDescription());
                eventType.setText("Type: " + event.getEventType());
                eventAddress.setText(event.getAddress());
                eventFee.setText("Signup fee: $" + event.getSignupFee());

                // Check if the event has a poster
                ImageView eventPoster = findViewById(R.id.EventPoster);
                if (event.getPosterUrl() != null && !event.getPosterUrl().isEmpty()) {
                    Glide.with(EventDetailsActivity.this)
                            .load(event.getPosterUrl())
                            .into(eventPoster);
                }

                // Date & time range
                if (event.getStartDate() != null && event.getEndDate() != null) {
                    SimpleDateFormat timeFmt = new SimpleDateFormat("hh:mm a");
                    SimpleDateFormat dateFmt = new SimpleDateFormat("MM/dd");
                    String dateRange = timeFmt.format(event.getStartDate().toDate())
                            + "-" + timeFmt.format(event.getEndDate().toDate())
                            + " from " + dateFmt.format(event.getStartDate().toDate())
                            + "-" + dateFmt.format(event.getEndDate().toDate());
                    eventDateRange.setText(dateRange);
                }

                // Draw date
                if (event.getDrawDate() != null) {
                    String drawStr = new SimpleDateFormat("MM/dd/yyyy").format(event.getDrawDate().toDate());
                    eventDrawDate.setText("Draws on " + drawStr);
                }

                // Spots available
                updateSpotsUI();

                // Check if user is already on waiting list
                db.collection("events")
                        .document(eventId)
                        .collection("waitingList")
                        .document(entrant.getDeviceId())
                        .get()
                        .addOnSuccessListener(doc -> {
                            isOnWaitingList = doc.exists();
                            updateToggleButton();
                        });
            }
        });

        // Toggle waiting list button
        btnToggleWaitingList.setOnClickListener(v -> {
            if (event == null) return;

            if (!isOnWaitingList) {

                // Check registration period before allowing join
                if (!isRegistrationOpen()) {
                    return;
                }

                // If user is an organizer, user cannot join waiting list
                if (Objects.equals(event.getOrganizerId(), deviceId) ||
                        (event.getCoOrganizerIds() != null && event.getCoOrganizerIds().contains(deviceId))) {
                    Toast.makeText(EventDetailsActivity.this,
                            "Organizers/Co-organizers cannot join waiting lists for their own events",
                            Toast.LENGTH_SHORT).show();
                    return;
                }

                // If waitlist is full, user cannot join
                if (event.getWaitlistLimit() != null && event.getCurrentWaitlistCount() >= event.getWaitlistLimit()) {
                    Toast.makeText(EventDetailsActivity.this, "Waitlist is full! Cannot join waiting list.", Toast.LENGTH_SHORT).show();
                    return;
                }

                // Join waiting list
                db.collection("events")
                        .document(event.getId())
                        .collection("waitingList")
                        .document(entrant.getDeviceId())
                        .set(new HashMap<String, Object>() {{
                            put("name", entrant.getName());
                            put("email", entrant.getEmail());
                            put("phone", entrant.getPhoneNumber());
                            put("status", "Waitlist");
                        }})
                        .addOnSuccessListener(aVoid -> {
                            isOnWaitingList = true;

                            db.collection("events")
                                    .document(event.getId())
                                    .update("currentWaitlistCount", FieldValue.increment(1))
                                    .addOnSuccessListener(unused -> {
                                        event.setCurrentWaitlistCount(event.getCurrentWaitlistCount() + 1);
                                        updateSpotsUI();
                                        updateToggleButton();
                                        Toast.makeText(EventDetailsActivity.this, "Joined waiting list!", Toast.LENGTH_SHORT).show();
                                    })
                                    .addOnFailureListener(e -> {
                                        isOnWaitingList = false;
                                        Toast.makeText(EventDetailsActivity.this, "Failed to update waitlist count", Toast.LENGTH_SHORT).show();
                                    });
                        })
                        .addOnFailureListener(e ->
                                Toast.makeText(EventDetailsActivity.this, "Failed to join waiting list", Toast.LENGTH_SHORT).show());
            } else {
                // Leave waiting list
                db.collection("events")
                        .document(event.getId())
                        .collection("waitingList")
                        .document(entrant.getDeviceId())
                        .delete()
                        .addOnSuccessListener(aVoid -> {
                            isOnWaitingList = false;

                            db.collection("events")
                                    .document(event.getId())
                                    .update("currentWaitlistCount", FieldValue.increment(-1))
                                    .addOnSuccessListener(unused -> {
                                        int newCount = Math.max(0, event.getCurrentWaitlistCount() - 1);
                                        event.setCurrentWaitlistCount(newCount);
                                        updateSpotsUI();
                                        updateToggleButton();
                                        Toast.makeText(EventDetailsActivity.this, "Left waiting list!", Toast.LENGTH_SHORT).show();
                                    })
                                    .addOnFailureListener(e -> {
                                        isOnWaitingList = true;
                                        Toast.makeText(EventDetailsActivity.this, "Failed to update waitlist count", Toast.LENGTH_SHORT).show();
                                    });
                        })
                        .addOnFailureListener(e ->
                                Toast.makeText(EventDetailsActivity.this, "Failed to leave waiting list", Toast.LENGTH_SHORT).show());
            }
        });

        // View comments fragment button

        btnViewComments = findViewById(R.id.btnViewComments);
        btnViewComments.setOnClickListener(v -> showCommentsDialog());

    }

    /**
     * Calculates the remaining spots available by subtracting the current waitlist
     * count from the total capacity, and updates the UI TextView accordingly.
     */
    void updateSpotsUI() {
        if (event == null) return;

        int capacity = event.getCapacity();
        int waitlistCount = Math.max(0, event.getCurrentWaitlistCount());
        int spotsAvailable = Math.max(0, capacity - waitlistCount);

        eventCapacity.setText(spotsAvailable + "/" + capacity + " spots available");
    }
    /**
     * Checks whether the current time falls within the event's registration period.
     *
     * @return true if registration is currently open, false otherwise
     */
    private boolean isRegistrationOpen() {
        Timestamp now = Timestamp.now();

        if (event.getRegistrationStart() != null &&
                now.compareTo(event.getRegistrationStart()) < 0) {
            Toast.makeText(this, "Registration has not opened yet.", Toast.LENGTH_SHORT).show();
            return false;
        }

        if (event.getRegistrationEnd() != null &&
                now.compareTo(event.getRegistrationEnd()) > 0) {
            Toast.makeText(this, "Registration period has ended.", Toast.LENGTH_SHORT).show();
            return false;
        }

        return true;
    }

    /**
     * Displays an info about the lottery selection criteria
     */
    private void showLotteryCriteriaDialog() {
        new androidx.appcompat.app.AlertDialog.Builder(this)
                .setTitle("Lottery Guidelines") // Set title
                .setMessage("Selection for this event is processed via a randomized lottery system.\n\n" + //message
                        "• Joining the waitlist does not guarantee entry.\n" +
                        "• When the draw date occurs, entrants are selected entirely at random up to the event's capacity limit.\n" +
                        "• If selected, you will receive a notification to finalize your enrollment.")
                .setPositiveButton("Understood", null) // dismiss message
                .show();
    }


    /**
     * Toggles the UI state of the waitlist button, changing its text and color
     * depending on whether the current user is already on the waiting list.
     */
    private void updateToggleButton() {
        if (isOnWaitingList) {
            btnToggleWaitingList.setText("Leave Waitlist");
            btnToggleWaitingList.setBackgroundTintList(getResources().getColorStateList(R.color.error, null));
        } else {
            btnToggleWaitingList.setText("Join Waitlist");
            btnToggleWaitingList.setBackgroundTintList(getResources().getColorStateList(R.color.accent, null));
        }
    }

    /**
     * Creates and displays a dialog containing a real-time feed of event comments,
     * along with an input field to submit new comments.
     */
    private void showCommentsDialog() {
        androidx.appcompat.app.AlertDialog.Builder builder = new androidx.appcompat.app.AlertDialog.Builder(this);
        builder.setTitle("Event Comments");

        // build the Dialog Layout dynamically
        LinearLayout mainLayout = new LinearLayout(this);
        mainLayout.setOrientation(LinearLayout.VERTICAL);
        mainLayout.setPadding(40, 24, 40, 24);

        // construct scrollable container for comments
        android.widget.ScrollView scrollView = new android.widget.ScrollView(this);
        LinearLayout commentsListLayout = new LinearLayout(this);
        commentsListLayout.setOrientation(LinearLayout.VERTICAL);
        scrollView.addView(commentsListLayout);

        // weight 1f to makes the scroll view take up all middle space, pushing input to the bottom
        LinearLayout.LayoutParams scrollParams = new LinearLayout.LayoutParams(
                LinearLayout.LayoutParams.MATCH_PARENT, 0, 1f);
        scrollParams.setMargins(0, 0, 0, 24);
        scrollView.setLayoutParams(scrollParams);

        // input container (EditText + Send Button)
        LinearLayout inputLayout = new LinearLayout(this);
        inputLayout.setOrientation(LinearLayout.HORIZONTAL);
        inputLayout.setGravity(android.view.Gravity.CENTER_VERTICAL);

        android.widget.EditText commentInput = new android.widget.EditText(this);
        commentInput.setHint("Write a comment...");
        commentInput.setLayoutParams(new LinearLayout.LayoutParams(0, LinearLayout.LayoutParams.WRAP_CONTENT, 1f));

        Button sendButton = new Button(this);
        sendButton.setText("Post");
        sendButton.setBackgroundColor(0xFF59A91E);
        sendButton.setTextColor(0xFFFFFFFF);

        inputLayout.addView(commentInput);
        inputLayout.addView(sendButton);

        // assemble the UI
        mainLayout.addView(scrollView);
        mainLayout.addView(inputLayout);
        builder.setView(mainLayout);
        builder.setPositiveButton("Close", null);

        androidx.appcompat.app.AlertDialog dialog = builder.create();

        // REAL-TIME FIRESTORE LISTENER
        // storing comments as a sub-collection under the specific event
        com.google.firebase.firestore.ListenerRegistration listener = db.collection("events")
                .document(eventId).collection("comments")
                .orderBy("timestamp", com.google.firebase.firestore.Query.Direction.ASCENDING)
                .addSnapshotListener((snapshots, e) -> {
                    if (e != null || snapshots == null) return;

                    commentsListLayout.removeAllViews(); // Clear and redraw

                    if (snapshots.isEmpty()) {
                        TextView tv = new TextView(this);
                        tv.setText("No comments yet. Be the first!");
                        tv.setTextColor(0xFF888888);
                        commentsListLayout.addView(tv);
                    }

                    for (DocumentSnapshot doc : snapshots.getDocuments()) {
                        com.example.getoutthere.models.Comment comment = doc.toObject(com.example.getoutthere.models.Comment.class);
                        if(comment != null) {
                            TextView tv = new TextView(this);
                            // Format: "Person: This event looks fun!"
                            android.text.SpannableString formattedText = new android.text.SpannableString(comment.getEntrantName() + ": " + comment.getContent());
                            formattedText.setSpan(new android.text.style.StyleSpan(android.graphics.Typeface.BOLD), 0, comment.getEntrantName().length() + 1, android.text.Spanned.SPAN_EXCLUSIVE_EXCLUSIVE);

                            tv.setText(formattedText);
                            tv.setTextSize(16f);
                            tv.setPadding(0, 8, 0, 16);
                            commentsListLayout.addView(tv);
                        }
                    }
                    // auto-scroll to bottom when new comment arrives
                    scrollView.post(() -> scrollView.fullScroll(View.FOCUS_DOWN));
                });

        //HANDLE POSTING COMMENTS
        sendButton.setOnClickListener(v -> {
            String text = commentInput.getText().toString().trim();
            if (text.isEmpty()) return;

            // debounce to prevent spam clicks
            sendButton.setEnabled(false);

            // fetch the user's name from their profile to attach it to the comment
            db.collection("profiles").document(entrant.getDeviceId()).get().addOnSuccessListener(doc -> {
                String userName = doc.exists() ? doc.getString("name") : "Anonymous User";

                com.example.getoutthere.models.Comment newComment = new com.example.getoutthere.models.Comment(
                        entrant.getDeviceId(),
                        userName,
                        text,
                        Timestamp.now()
                );

                db.collection("events").document(eventId).collection("comments").add(newComment)
                        .addOnSuccessListener(docRef -> {
                            commentInput.setText(""); // Clear input on success
                            sendButton.setEnabled(true);
                        })
                        .addOnFailureListener(e -> {
                            Toast.makeText(this, "Failed to post comment", Toast.LENGTH_SHORT).show();
                            sendButton.setEnabled(true);
                        });
            });
        });

        // clean up the listener when dialog closes to save memory
        dialog.setOnDismissListener(d -> listener.remove());

        dialog.show();

        // ensure the dialog takes up a good amount of vertical space
        dialog.getWindow().setLayout(android.view.ViewGroup.LayoutParams.MATCH_PARENT, 1200);
    }

}